import type { ResolvedToken } from '../types.js'

/**
 * Generates a typed ES module that exports each token as a named constant.
 *
 * Usage in consumer code:
 *   import { colorBackgroundPrimary } from '@myds/tokens/js'
 *   // → 'var(--ds-color-background-primary)'
 */
export function generateJS(tokens: ResolvedToken[]): string {
  const lines = tokens.map((t) => {
    const ident = toCamelCase(t.name)
    const comment = t.description ? ` // ${t.description}` : ''
    return `export const ${ident} = ${JSON.stringify(t.cssVar)}${comment}`
  })

  return `// Auto-generated by @dsbuilder/tokens — do not edit manually\n\n${lines.join('\n')}\n`
}

export function generateDTS(tokens: ResolvedToken[]): string {
  const lines = tokens.map((t) => {
    const ident = toCamelCase(t.name)
    const comment = t.description
      ? `/** ${t.description} — type: ${t.type} */\n`
      : `/** type: ${t.type} */\n`
    return `${comment}export declare const ${ident}: string`
  })

  return `// Auto-generated by @dsbuilder/tokens — do not edit manually\n\n${lines.join('\n')}\n`
}

function toCamelCase(dotPath: string): string {
  return dotPath
    .split('.')
    .map((segment, i) =>
      i === 0 ? segment : segment.charAt(0).toUpperCase() + segment.slice(1),
    )
    .join('')
}
